* 5.3 Exercises
** Review Questions
*** 1. What kind of values are reported for Erlang’s memory?
*** 2. What’s a valuable process-related metric for a global view?
*** 3. What’s a port, and how should it be monitored globally?
*** 4. Why can’t you trust top or htop for CPU usage with Erlang systems? What’s the alternative?
*** 5. Name two types of signal-related information available for processes.
*** 6. How can you find what code a specific process is running?
*** 7. What are the different kinds of memory information available for a specific process?
*** 8. How can you know if a process is doing a lot of work?
*** 9. Name a few of the values that are dangerous to fetch when inspecting processes in a production system.
*** 10. What are some features provided to OTP processes through the sys module?
*** 11. What kind of values are available when inspecting inet ports?
*** 12. How can you find the type of a port (Files, TCP, UDP)?
** Open-ended Questions
*** 1. Why do you want a long time window available on global metrics?
*** 2. Which would be more appropriate between recon:proc_count/2 and recon:proc_window/3 to find issues with: Reductions, Memory, Message queue length?
*** 3. How can you find information about who is the supervisor of a given process?
*** 4. When should you use recon:inet_count/2? recon:inet_window/3?
*** 5. What could explain the difference in memory reported by the operating system and the memory functions in Erlang?
*** 6. Why is it that Erlang can sometimes look very busy even when it isn’t?
*** 7. How can you find what proportion of processes on a node are ready to run, but can’t be scheduled right away?
** Hands-On
*** 1. What’s the system memory?
*** 2. Is the node using a lot of CPU resources?
*** 3. Is any process mailbox overflowing?
*** 4. Which chatty process (council_member) takes the most memory?
*** 5. Which chatty process is eating the most CPU?
*** 6. Which chatty process is consuming the most bandwidth?
*** 7. Which chatty process sends the most messages over TCP? The least?
*** 8. Can you find out if a specific process tends to hold multiple connections or file descriptors open at the same time on a node?
*** 9. Can you find out which function is being called by the most processes at once on the node right now?
